### PR TITLE
Merging changes from kepler-twowheel code on Sourceforge.

### PR DESCRIPTION
**Pull request by fergalm**
This pull request merges changes from my independent development of fov.py over the last two years. It adds unit tests, and improved functionality for fov.py. 

Some of the more important details.
- Code to check that a position lands on silicon now include optional padding arguments which makes it easier to compensate for any errors in the focal plane model.
- KeplerFov now has an isOnSilicon() method.
- K2OnSilicons' onSiliconCheck now calls KeplerFov.isOnSilicon() instead of pickAChannel(). pickAChannel now returns the nearest channel to a requested ra/dec, where previously it raised an exception if it thought the ra/dec was off silicon. This makes the padding argument above easier to implement. 
- The Gnomic Projection class now plots views with RA decreasing from left to right, as is astronomical convention.
- fov.py uses a newer, easier to read module for handling Eulerian rotations, rotate2.py

### CODE REVIEW

**Comment by barentsen** [comment]
@mrtommyb Fergal and I debugged this today to make sure all the unit tests work on Python 2.6 through 3.5.  I fetched this branch, played with it, and think you are safe to merge this.

Let's not push it as a new version to PyPi yet.  I plan on adding a tool shortly, called `K2visible`, that tells the user which campaigns a position on the sky is in or near.

**Comment by barentsen** [comment]
I believe the most important end-user change here is that `K2onSilicon.onSiliconCheck()` will now return `True` for objects though to lie outside silicon by less than 10 pixels, whereas previously it returned `False`.

@fergalm Can you confirm that my understanding is correct?
@mrtommyb Does this sound ok, or is the 10 pixel padding perhaps a bit generous?

I've tagged v2.0.1 (the most recent stable version) as a release on GitHub so we can easily revert back if something goes wrong.

**Comment by mrtommyb** [comment]
I _think_ this sounds fine. Let's think about this until tomorrow

**Comment by fergalm** [comment]
For the outer modules my limited testing suggested the accuracy of the
conversion from ra/dec to col row was no better than about that level. By
adding the padding we ensure no targets are rejected due to the
imperfections of this code, when TAD might let them through. I think this
is the right thing to do, but it may result in unhappy end users who think
they get to observe their targets but find out much later (after the review
process) that they don't.

Fergal

**Comment by mrtommyb** [comment]
I've thought about tis some more. 
@fergalm the accuracy at the edge of the field _is_ better than 10 pixels. We have tested this by putting stars that are near the edge of the fov on the target list, it's good to around 3 pixels. I suggest we change the padding to a maximum of 5 pixels.

**Comment by mrtommyb** [comment]
bah, it's probably ok to leave the padding as is. I'm just concern that we are making changes to something that was working.

**Comment by barentsen** [comment]
After chatting with Tom about it earlier today, I changed the default padding to 3px tonight (commit 8becb2bd129126bdcbb859eb67b07a6e1926d94b).

@fergalm Please let us know if this change negatively affects your code.  All unit tests still pass (and I've been adding a few more tonight to make sure the recent code changes don't bite us).

**Comment by fergalm** [comment]
A unit test that shows this padding is accurate (compared to say TAD) would be a nice addition. Do we have easy access to a TAD ra/dec -> channel col row conversion?

**Comment by barentsen** [comment]
@fergalm How is the WCS in TPF headers arrived at?  If there is a reason to believe that the WCS is accurate, we could harvest a bunch of (col, row, ra, dec) tuples from a sample of TPF files and use that as a test case.  Would that make sense?  I can volunteer to do the harvest.

**Comment by fergalm** [comment]
I think it's best to go directly to source. The WCS is an approximation of how TAD works. I  think it's good to an arcsec or so, but it's a much better plan to use TAD directly. @mrtommyb can probably tell us how well the TPF WCS has been tested.

**Pull request merged**
